### ISSUE TITLE
Add inference of ancestral states

### ISSUE THREAD

**Issue by sdwfrost** [emvolz-phylodynamics/phyland#4]
To better compare with BEAST output, it would be good to generate estimates of ancestral states at each node in the tree at the ML parameter estimates.

**Comment by emvolz** [comment]
I added the `ace` option (default FALSE)
If true, it returns a list of interpolating functions for each lineages. Note these are in the order of $bdt$edge.list. These return a vector of probabilities for each deme, eg
> f$ace[[16]](.40)
Error in f$ace[[16]](0.4) : 
  Lineage is not extant at given time before most recent sample. Lineage is extant:  0 , 0.346162158894003  time units before most recent sample.
> f$ace[[16]](.20)
    Human       Pig 
0.4412319 0.5587681
